const CategoriesList = [
  {
    id: "3",
    type: "mattress",
    label: "მატრასი",
    labelEn: "Mattress",
    quantity: 3,
    image: "/mattress.jpg",
  },
  {
    id: "4",
    type: "bed",
    label: "საწოლი",
    labelEn: "Bed",
    quantity: 5,
    image: "/bed1.jpg",
  },
  {
    id: "2",
    type: "pillow",
    label: "ბალიში",
    labelEn: "Pillow",
    quantity: 2,
    image: "/photo_2025-07-19_08-19-19.jpg",
  },
  {
    id: "5",
    type: "quilt",
    label: "საბანი",
    labelEn: "Quilt",
    quantity: 7,
    image: "/quilttt.jpg",
  },
  {
    id: "7",
    type: "pad",
    label: "ტოპერი",
    labelEn: "Topper",
    quantity: 3,
    image: "/mattress.jpg",
  },
  {
    id: "8",
    type: "linen",
    label: "თეთრეული",
    labelEn: "Bedding & linen",
    quantity: 7,
    image: "/bed1.jpg",
  },
  {
    id: "9",
    type: "protector",
    label: "დამცავები",
    labelEn: "Protectors",
    quantity: 7,
    image: "/mattress.jpg",
  },
  {
    id: "6",
    type: "OTHERS",
    label: "სხვა",
    labelEn: "Others",
    quantity: 7,
    image: "/khampha-phimmachak-vdkAt1S7fCc-unsplash.jpg",
  },
];

export default CategoriesList;
